name: Excavator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  excavate:
    name: Excavate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Excavate
        uses: moeshin/Scoop-GithubActions@stable
        env:
          GITHUB_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: '1'
