name: Excavator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # SKIP_UPDATED: '1'
          SCOOP_BRANCH: main
